MenuPermit.create(name: 'Empleados', tab_reference: 'employees', tab_icon: 'ti-user', available_for_client: false, order: 1, default: true)
MenuPermit.create(name: 'Cliente', tab_reference: 'clients', tab_icon: 'ti-user', available_for_client: false, order: 2, default: true)
MenuPermit.create(name: 'Inventario', tab_reference: 'inventories', tab_icon: 'ti-bar-chart-alt', available_for_client: false, order: 3, default: true)
MenuPermit.create(name: 'Laboratorios', tab_reference: 'laboratories', tab_icon: 'ti-ruler', available_for_client: false, order: 4, default: true)
MenuPermit.create(name: 'Metodos de Ensayo', tab_reference: 'sample_methods', tab_icon: 'ti-receipt', available_for_client: false, order: 6, default: true)
MenuPermit.create(name: 'Solicitudes de servicio', tab_reference: 'check_services', tab_icon: 'ti-clipboard', available_for_client: false, order: 6, default: true)
MenuPermit.create(name: 'Cadena de Custodia', tab_reference: 'classified_services', tab_icon: 'ti-hummer', available_for_client: false, order: 7, default: false)
MenuPermit.create(name: 'Orden de Custodia', tab_reference: 'work_classified_services', tab_icon: 'ti-hummer', available_for_client: false, order: 7, default: false)
MenuPermit.create(name: 'Solicitudes de servicio', tab_reference: 'services', tab_icon: 'ti-hummer', available_for_client: true, order: 8, default: true)
MenuPermit.create(name: 'Ejecución de servicios', tab_reference: 'services', tab_icon: 'ti-hummer', available_for_client: false, order: 8, default: true)
MenuPermit.create(name: 'Proformas', tab_reference: 'quotations', tab_icon: 'ti-clipboard', available_for_client: true, order: 8, default: true)
MenuPermit.create(name: 'Orden de Trabajo', tab_reference: 'work_orders', tab_icon: 'ti-hummer', available_for_client: false, order: 9, default: true)
MenuPermit.create(name: 'Roles', tab_reference: 'roles', tab_icon: 'ti-id-badge', available_for_client: false, order: 10, default: true)
MenuPermit.create(name: 'Logs', tab_reference: 'logs', tab_icon: 'ti-write', available_for_client: false, order: 12, default: true)