MenuPermit.create(name: 'Empleados', tab_reference: 'employees', tab_icon: 'ti-user', available_for_client: false, order: 1, default: true)
MenuPermit.create(name: 'Cliente', tab_reference: 'clients', tab_icon: 'ti-user', available_for_client: false, order: 2, default: true)
MenuPermit.create(name: 'Inventario', tab_reference: 'inventories', tab_icon: 'ti-bar-chart-alt', available_for_client: false, order: 3, default: true)
MenuPermit.create(name: 'Muestras', tab_reference: 'samples', tab_icon: 'ti-package', available_for_client: true, order: 4, default: true)
MenuPermit.create(name: 'Cotizaciones', tab_reference: 'quotations', tab_icon: 'ti-clipboard', available_for_client: true, order: 5, default: true)
MenuPermit.create(name: 'Resultados', tab_reference: 'results', tab_icon: 'ti-view-list-alt', available_for_client: true, order: 6, default: true)
MenuPermit.create(name: 'Orden de Trabajo', tab_reference: 'work_orders', tab_icon: 'ti-hummer', available_for_client: true, order: 7, default: true)
MenuPermit.create(name: 'Solicitudes de Servicio', tab_reference: 'requests', tab_icon: 'ti-clipboard', available_for_client: true, order: 8, default: true)
MenuPermit.create(name: 'Cotizacion de Servicio', tab_reference: 'service_quotations', tab_icon: 'ti-clipboard', available_for_client: true, order: 9, default: true)
MenuPermit.create(name: 'Servicio', tab_reference: 'sample_methods', tab_icon: 'ti-receipt', available_for_client: false, order: 10, default: true)
MenuPermit.create(name: 'Laboratorios', tab_reference: 'laboratories', tab_icon: 'ti-ruler', available_for_client: false, order: 11, default: true)
MenuPermit.create(name: 'Roles', tab_reference: 'roles', tab_icon: 'ti-id-badge', available_for_client: false, order: 12, default: true)
MenuPermit.create(name: 'Logs', tab_reference: 'logs', tab_icon: 'ti-write', available_for_client: false, order: 13, default: true)