MenuPermit.create(name: 'Empleados')
MenuPermit.create(name: 'Cliente')
MenuPermit.create(name: 'Inventario')
MenuPermit.create(name: 'Muestras')
MenuPermit.create(name: 'Cotizaciones')
MenuPermit.create(name: 'Resultados')
MenuPermit.create(name: 'Orden de Trabajo')
MenuPermit.create(name: 'Solicitudes de Servicio')
MenuPermit.create(name: 'Cotizacion de Servicio')
MenuPermit.create(name: 'Servicio')
MenuPermit.create(name: 'Laboratorios')
MenuPermit.create(name: 'Roles')
MenuPermit.create(name: 'Logs')


