Role.create(name: "Jefe de Laboratorio", description: "test", laboratory_id: 1, status: 0)
MenuPermit.create(name: 'Empleados', tab_reference: 'employees', tab_icon: 'ti-user', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Cliente', tab_reference: 'clients', tab_icon: 'ti-user', available_for_client: false, order: nil, default: false, role_id: 1)	
MenuPermit.create(name: 'Inventario', tab_reference: 'inventories', tab_icon: 'ti-bar-chart-alt', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Metodos de Ensayo', tab_reference: 'sample_methods', tab_icon: 'ti-receipt', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Solicitudes de servicio', tab_reference: 'check_services', tab_icon: 'ti-clipboard', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Proformas', tab_reference: 'quotations', tab_icon: 'ti-clipboard', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Revision de servicios', tab_reference: 'services', tab_icon: 'ti-hummer', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Clasificacion de servicios', tab_reference: 'classified_services', tab_icon: 'ti-hummer', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Orden de Trabajo', tab_reference: 'work_orders', tab_icon: 'ti-hummer', available_for_client: false, order: nil, default: false, role_id: 1)
MenuPermit.create(name: 'Roles', tab_reference: 'roles', tab_icon: 'ti-id-badge', available_for_client: false, order: nil, default: false, role_id: 1)
Role.create(name: "Analista", description: "test", laboratory_id: 1, status: 0)
MenuPermit.create(name: 'Solicitudes de servicio', tab_reference: 'services', tab_icon: 'ti-clipboard', available_for_client: false, order: nil, default: false, role_id: 2)
MenuPermit.create(name: 'Proformas', tab_reference: 'quotations', tab_icon: 'ti-clipboard', available_for_client: false, order: nil, default: false, role_id: 2)
MenuPermit.create(name: 'Orden de Trabajo', tab_reference: 'work_orders', tab_icon: 'ti-hummer', available_for_client: false, order: nil, default: false, role_id: 2)