User.create(email: 'sical@pucp.pe', password: "pucppass2017", status: 0, category: 0)
User.create(name: 'Jefe de Laboratorio', email: 'jefe_lab@pucp.pe', password: "pucppass2017", status: 0, category: 1, laboratory_id: 1, role_id: 1)
User.create(name: 'Analista X', email: 'empleado@pucp.pe', password: "pucppass2017", status: 0, category: 1, laboratory_id: 1, role_id: 2)
User.create(name: 'Analista Y', email: 'john_doe@pucp.pe', password: "pucppass2017", status: 0, category: 1, laboratory_id: 1, role_id: 2)
User.create(name: 'cliente', email: 'cliente@pucp.pe', password: "pucppass2017", status: 0, category: 2)
